services:
  web:
    image: nginx:alpine
    container_name: static_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_app
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: daniil05042012
      POSTGRES_DB: kdmsenter_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database_postgresql.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata: